# fly.toml app configuration file generated for shy-cloud-3319 on 2023-08-18T16:09:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-cloud-3319"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
